name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build system images (non-pulling)
        run: |
          # build base image
          docker-compose -f ./deploy/docker-compose.dev.yml build --no-cache
      - name: Run docker-compose
        run: |
          docker-compose -f ./deploy/docker-compose.dev.yml up --force-recreate --remove-orphans -d
          sleep 30
      - name: Run tests
        run: |
          curl http://localhost:8080
          curl http://localhost:8000
      - name: Selenium tests
        run: |
          pip install -r ./tests/requirements.txt
          python ./tests/basic_test.py
